### PR TITLE
Update kernel

### PR DESCRIPTION
**Pull request by aykevl**
The kernel we use has been updated. The change relevant for TWRP is the last commit: 2c6571a658b3585e9b2e3583d04dde85cc8fd847. It disables some security restrictions that disable the process named "adbd", fixing `adb shell`.

Pulling in all changes to keep the two repositories in sync.

### CODE REVIEW

**Comment by bigbiff** [comment]
You will need to push this to the project at gerrit.twrp.me

**Comment by aykevl** [comment]
It looks like the project isn't available on gerrit.twrp.me.
https://gerrit.twrp.me/#/admin/projects/?filter=kminilte

**Comment by bigbiff** [comment]
Sorry, I have created the project on the site for pushing.

**Comment by aykevl** [comment]
I have tried to, but I can't push it to Gerrit:

* There is no `android-7.1` branch (only `cm-14.1` which I think is incorrect).
* I haven't created all commits, so Gerrit refuses to accept them.

```
remote: ERROR:  In commit 117a290ceefd1eb14eda6565c8a62f444eb4f9e2
remote: ERROR:  committer email address hennymcc@<redacted>
remote: ERROR:  does not match your user account.
remote: ERROR:
remote: ERROR:  The following addresses are currently registered:
remote: ERROR:    <my email address>
remote: ERROR:
remote: ERROR:  To register an email address, please visit:
remote: ERROR:  https://gerrit.twrp.me/#/settings/contact
```

**Comment by bigbiff** [comment]
I created the android-7.1 branch in gerrit. Did you register your email in gerrit.twrp.me?

**Comment by aykevl** [comment]
Thank you.
Yes I've registered my email address, but there are many commits that aren't created by me (thus have a different email address). I could of course only submit the last commit, but that would diverge the history.

**Comment by bigbiff** [comment]
I guess I don't understand what you are trying to do. Can you layout your workflow and your intentions?

**Comment by aykevl** [comment]
In the upstream kminilte kernel there were many changes (not by me) and after that one commit (by me) that fixes adb in TWRP.

So there are two options now:

* Merge all commits up to and including my commit, keeping histories in sync. I can't send a change request for this because I haven't authored all those commits.
* Cherry-pick this single commit and create a change request in Gerrit. I can easily do this, but it will diverge the kernel history.

I would prefer the former option.

**Comment by bigbiff** [comment]
I guess I could give you the ability to force push to the head on gerrit, and turn off fast foward at github. What do you think?

**Comment by aykevl** [comment]
I don't know what you mean?
I know a bit about git (I know what fast-forward means) but I'm new to Gerrit or any connection between GitHub and Gerrit.
But if you tell me wat to do I can do it.

**Comment by aykevl** [comment]
If I understand it right, yes that sounds good.

**Comment by bigbiff** [comment]
I added you to the gerrit group. Are you able to force push to
refs/heads/branch?

**Comment by aykevl** [comment]
Yes, it looks like the head is now at the correct commit (2c6571a658b3585e9b2e3583d04dde85cc8fd847). Thank you!

```
~/src/android_kernel_samsung_kminilte$ git push omnirom HEAD:refs/heads/android-7.1
Counting objects: 421, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (103/103), done.
Writing objects: 100% (421/421), 117.11 KiB | 0 bytes/s, done.
Total 421 (delta 316), reused 397 (delta 297)
remote: Resolving deltas: 100% (316/316)
remote: Processing changes: refs: 1, done    
remote: (W) 2d5f224: commit subject >50 characters; use shorter first paragraph
remote: (W) 00c40ea: commit subject >50 characters; use shorter first paragraph
remote: (W) 04626aa: commit subject >50 characters; use shorter first paragraph
remote: (W) 028ec22: commit subject >50 characters; use shorter first paragraph
remote: (W) e6f8039: commit subject >50 characters; use shorter first paragraph
remote: (W) b5266fc: commit subject >50 characters; use shorter first paragraph
remote: (W) 3135403: commit subject >50 characters; use shorter first paragraph
remote: (W) 2353838: commit subject >50 characters; use shorter first paragraph
remote: (W) 3cd7020: commit subject >50 characters; use shorter first paragraph
remote: (W) 26162a6: commit subject >50 characters; use shorter first paragraph
remote: (W) b3e107f: commit subject >50 characters; use shorter first paragraph
remote: (W) cb28dcf: commit subject >50 characters; use shorter first paragraph
remote: (W) bee26ee: commit subject >50 characters; use shorter first paragraph
remote: (W) 8bdc4a7: commit subject >50 characters; use shorter first paragraph
remote: (W) 8bdc4a7: too many commit message lines longer than 72 characters; manually wrap lines
remote: (W) c98343d: commit subject >50 characters; use shorter first paragraph
remote: (W) 3b47c0c: commit subject >50 characters; use shorter first paragraph
remote: (W) 2e5f410: commit subject >50 characters; use shorter first paragraph
remote: (W) dbb1413: commit subject >50 characters; use shorter first paragraph
remote: (W) 0a53d93: commit subject >50 characters; use shorter first paragraph
remote: (W) 0a53d93: too many commit message lines longer than 72 characters; manually wrap lines
remote: (W) ebb5648: commit subject >50 characters; use shorter first paragraph
remote: (W) d51a662: commit subject >50 characters; use shorter first paragraph
remote: (W) 9479413: commit subject >50 characters; use shorter first paragraph
remote: (W) 48e1abf: commit subject >50 characters; use shorter first paragraph
remote: (W) 4c2b78f: commit subject >50 characters; use shorter first paragraph
remote: (W) 7a42fe2: commit subject >50 characters; use shorter first paragraph
remote: (W) b33995f: commit subject >50 characters; use shorter first paragraph
remote: (W) 117a290: commit subject >50 characters; use shorter first paragraph
To ssh://gerrit.twrp.me:29418/android_kernel_samsung_kminilte
   ff00db8c954..2c6571a658b  HEAD -> android-7.1
```

**Pull request closed without merging**
